
//          Copyright Joseph Dobson, Andrea Zanellato 2014
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

#include "command.hpp"

#include <stdexcept>

//generated using:
// s/^\s*\(ERR_\w*\).*/\tcase static_cast<raw_command_t>(\1):/p
// s/^\s*\(RPL_\w*\).*/\tcase static_cast<raw_command_t>(\1):/p

namespace irc {

command to_command(raw_command_t value) {
	switch(value) {
	default:
		throw std::runtime_error("value not an enum value");
	case static_cast<raw_command_t>(RPL_WELCOME):
	case static_cast<raw_command_t>(RPL_YOURHOST):
	case static_cast<raw_command_t>(RPL_CREATED):
	case static_cast<raw_command_t>(RPL_MYINFO):
	case static_cast<raw_command_t>(RPL_BOUNCE):
	case static_cast<raw_command_t>(RPL_PROTOCTL):
	case static_cast<raw_command_t>(RPL_MAPMORE):
	case static_cast<raw_command_t>(RPL_MAPEND):
	case static_cast<raw_command_t>(RPL_SNOMASK):
	case static_cast<raw_command_t>(RPL_STATMEMTOT):
	case static_cast<raw_command_t>(RPL_STATMEM):
	case static_cast<raw_command_t>(RPL_YOURCOOKIE):
	case static_cast<raw_command_t>(RPL_TRACELINK):
	case static_cast<raw_command_t>(RPL_TRACECONNECTING):
	case static_cast<raw_command_t>(RPL_TRACEHANDSHAKE):
	case static_cast<raw_command_t>(RPL_TRACEUNKNOWN):
	case static_cast<raw_command_t>(RPL_TRACEOPERATOR):
	case static_cast<raw_command_t>(RPL_TRACEUSER):
	case static_cast<raw_command_t>(RPL_TRACESERVER):
	case static_cast<raw_command_t>(RPL_TRACESERVICE):
	case static_cast<raw_command_t>(RPL_TRACENEWTYPE):
	case static_cast<raw_command_t>(RPL_TRACECLASS):
	case static_cast<raw_command_t>(RPL_TRACERECONNECT):
	case static_cast<raw_command_t>(RPL_STATSLINKINFO):
	case static_cast<raw_command_t>(RPL_STATSCOMMANDS):
	case static_cast<raw_command_t>(RPL_STATSCLINE):
	case static_cast<raw_command_t>(RPL_STATSNLINE):
	case static_cast<raw_command_t>(RPL_STATSILINE):
	case static_cast<raw_command_t>(RPL_STATSKLINE):
	case static_cast<raw_command_t>(RPL_STATSQLINE):
	case static_cast<raw_command_t>(RPL_STATSYLINE):
	case static_cast<raw_command_t>(RPL_ENDOFSTATS):
	case static_cast<raw_command_t>(RPL_UMODEIS):
	case static_cast<raw_command_t>(RPL_STATSBLINE):
	case static_cast<raw_command_t>(RPL_STATSELINE):
	case static_cast<raw_command_t>(RPL_STATSFLINE):
	case static_cast<raw_command_t>(RPL_STATSDLINE):
	case static_cast<raw_command_t>(RPL_STATSZLINE):
	case static_cast<raw_command_t>(RPL_STATSCOUNT):
	case static_cast<raw_command_t>(RPL_STATSGLINE):
	case static_cast<raw_command_t>(RPL_SERVICEINFO):
	case static_cast<raw_command_t>(RPL_ENDOFSERVICES):
	case static_cast<raw_command_t>(RPL_SERVICE):
	case static_cast<raw_command_t>(RPL_SERVLIST):
	case static_cast<raw_command_t>(RPL_SERVLISTEND):
	case static_cast<raw_command_t>(RPL_STATSVLINE):
	case static_cast<raw_command_t>(RPL_STATSLLINE):
	case static_cast<raw_command_t>(RPL_STATSUPTIME):
	case static_cast<raw_command_t>(RPL_STATSOLINE):
	case static_cast<raw_command_t>(RPL_STATSHLINE):
	case static_cast<raw_command_t>(RPL_STATSPING):
	case static_cast<raw_command_t>(RPL_STATSULINE):
	case static_cast<raw_command_t>(RPL_STATSBLINE):
	case static_cast<raw_command_t>(RPL_STATSXLINE):
	case static_cast<raw_command_t>(RPL_STATSDEFINE):
	case static_cast<raw_command_t>(RPL_STATSULINE):
	case static_cast<raw_command_t>(RPL_STATSDEBUG):
	case static_cast<raw_command_t>(RPL_STATSDLINE):
	case static_cast<raw_command_t>(RPL_LUSERCLIENT):
	case static_cast<raw_command_t>(RPL_LUSEROP):
	case static_cast<raw_command_t>(RPL_LUSERUNKNOWN):
	case static_cast<raw_command_t>(RPL_LUSERCHANNELS):
	case static_cast<raw_command_t>(RPL_USERUNKNOWN):
	case static_cast<raw_command_t>(RPL_LUSERME):
	case static_cast<raw_command_t>(RPL_ADMINME):
	case static_cast<raw_command_t>(RPL_ADMINLOC1):
	case static_cast<raw_command_t>(RPL_ADMINLOC2):
	case static_cast<raw_command_t>(RPL_ADMINEMAIL):
	case static_cast<raw_command_t>(RPL_ADMINME):
	case static_cast<raw_command_t>(RPL_TRACELOG):
	case static_cast<raw_command_t>(RPL_TRACELINK):
	case static_cast<raw_command_t>(RPL_TRACENEWTYPE):
	case static_cast<raw_command_t>(RPL_TRACEEND):
	case static_cast<raw_command_t>(RPL_TRACEEND):
	case static_cast<raw_command_t>(RPL_ENDOFTRACE):
	case static_cast<raw_command_t>(RPL_TRACEPING):
	case static_cast<raw_command_t>(RPL_TRYAGAIN):
	case static_cast<raw_command_t>(RPL_LOCALUSERS):
	case static_cast<raw_command_t>(RPL_GLOBALUSERS):
	case static_cast<raw_command_t>(RPL_SILELIST):
	case static_cast<raw_command_t>(RPL_ENDOFSILELIST):
	case static_cast<raw_command_t>(RPL_STATSDELTA):
	case static_cast<raw_command_t>(RPL_STATSDLINE):
	case static_cast<raw_command_t>(RPL_GLIST):
	case static_cast<raw_command_t>(RPL_ENDOFGLIST):
	case static_cast<raw_command_t>(RPL_HELPHDR):
	case static_cast<raw_command_t>(RPL_HELPOP):
	case static_cast<raw_command_t>(RPL_HELPTLR):
	case static_cast<raw_command_t>(RPL_HELPHLP):
	case static_cast<raw_command_t>(RPL_HELPFWD):
	case static_cast<raw_command_t>(RPL_HELPIGN):
	case static_cast<raw_command_t>(RPL_NONE):
	case static_cast<raw_command_t>(RPL_AWAY):
	case static_cast<raw_command_t>(RPL_USERHOST):
	case static_cast<raw_command_t>(RPL_ISON):
	case static_cast<raw_command_t>(RPL_UNAWAY):
	case static_cast<raw_command_t>(RPL_AWAY):
	case static_cast<raw_command_t>(RPL_AWAY):
	case static_cast<raw_command_t>(RPL_NOWAWAY):
	case static_cast<raw_command_t>(RPL_WHOISREGNICK):
	case static_cast<raw_command_t>(RPL_WHOISADMIN):
	case static_cast<raw_command_t>(RPL_WHOISSADMIN):
	case static_cast<raw_command_t>(RPL_WHOISSVCMSG):
	case static_cast<raw_command_t>(RPL_WHOISUSER):
	case static_cast<raw_command_t>(RPL_WHOISSERVER):
	case static_cast<raw_command_t>(RPL_WHOISOPERATOR):
	case static_cast<raw_command_t>(RPL_WHOWASUSER):
	case static_cast<raw_command_t>(RPL_ENDOFWHO):
	case static_cast<raw_command_t>(RPL_WHOISCHANOP):
	case static_cast<raw_command_t>(RPL_WHOISIDLE):
	case static_cast<raw_command_t>(RPL_ENDOFWHOIS):
	case static_cast<raw_command_t>(RPL_WHOISCHANNELS):
	case static_cast<raw_command_t>(RPL_LISTSTART):
	case static_cast<raw_command_t>(RPL_LIST):
	case static_cast<raw_command_t>(RPL_LISTEND):
	case static_cast<raw_command_t>(RPL_CHANNELMODEIS):
	case static_cast<raw_command_t>(RPL_UNIQOPIS):
	case static_cast<raw_command_t>(RPL_CHPASSUNKNOWN):
	case static_cast<raw_command_t>(RPL_CREATIONTIME):
	case static_cast<raw_command_t>(RPL_NOTOPIC):
	case static_cast<raw_command_t>(RPL_TOPIC):
	case static_cast<raw_command_t>(RPL_LISTUSAGE):
	case static_cast<raw_command_t>(RPL_COMMANDSYNTAX):
	case static_cast<raw_command_t>(RPL_CHANPASSOK):
	case static_cast<raw_command_t>(RPL_BADCHANPASS):
	case static_cast<raw_command_t>(RPL_INVITING):
	case static_cast<raw_command_t>(RPL_SUMMONING):
	case static_cast<raw_command_t>(RPL_INVITELIST):
	case static_cast<raw_command_t>(RPL_INVITELIST):
	case static_cast<raw_command_t>(RPL_ENDOFINVITELIST):
	case static_cast<raw_command_t>(RPL_EXCEPTLIST):
	case static_cast<raw_command_t>(RPL_EXCEPTLIST):
	case static_cast<raw_command_t>(RPL_ENDOFEXCEPTLIST):
	case static_cast<raw_command_t>(RPL_VERSION):
	case static_cast<raw_command_t>(RPL_WHOREPLY):
	case static_cast<raw_command_t>(RPL_NAMREPLY):
	case static_cast<raw_command_t>(RPL_KILLDONE):
	case static_cast<raw_command_t>(RPL_CLOSING):
	case static_cast<raw_command_t>(RPL_CLOSEEND):
	case static_cast<raw_command_t>(RPL_LINKS):
	case static_cast<raw_command_t>(RPL_ENDOFLINKS):
	case static_cast<raw_command_t>(RPL_ENDOFNAMES):
	case static_cast<raw_command_t>(RPL_BANLIST):
	case static_cast<raw_command_t>(RPL_BANLIST):
	case static_cast<raw_command_t>(RPL_ENDOFBANLIST):
	case static_cast<raw_command_t>(RPL_ENDOFWHOWAS):
	case static_cast<raw_command_t>(RPL_INFO):
	case static_cast<raw_command_t>(RPL_MOTD):
	case static_cast<raw_command_t>(RPL_INFOSTART):
	case static_cast<raw_command_t>(RPL_ENDOFINFO):
	case static_cast<raw_command_t>(RPL_MOTDSTART):
	case static_cast<raw_command_t>(RPL_ENDOFMOTD):
	case static_cast<raw_command_t>(RPL_ENDOFMOTD):
	case static_cast<raw_command_t>(RPL_YOUREOPER):
	case static_cast<raw_command_t>(RPL_REHASHING):
	case static_cast<raw_command_t>(RPL_YOURESERVICE):
	case static_cast<raw_command_t>(RPL_MYPORTIS):
	case static_cast<raw_command_t>(RPL_TIME):
	case static_cast<raw_command_t>(RPL_USERSSTART):
	case static_cast<raw_command_t>(RPL_USERS):
	case static_cast<raw_command_t>(RPL_ENDOFUSERS):
	case static_cast<raw_command_t>(RPL_USERSSTART):
	case static_cast<raw_command_t>(RPL_NOUSERS):
	case static_cast<raw_command_t>(RPL_LOGOFF):
	case static_cast<raw_command_t>(RPL_WATCHOFF):
	case static_cast<raw_command_t>(RPL_WATCHSTAT):
	case static_cast<raw_command_t>(RPL_NOWON):
	case static_cast<raw_command_t>(RPL_NOWOFF):
	case static_cast<raw_command_t>(RPL_WATCHLIST):
	case static_cast<raw_command_t>(RPL_ENDOFWATCHLIST):
	case static_cast<raw_command_t>(RPL_DCCSTATUS):
	case static_cast<raw_command_t>(RPL_DCCLIST):
	case static_cast<raw_command_t>(RPL_ENDOFDCCLIST):
	case static_cast<raw_command_t>(RPL_DCCINFO):
	case static_cast<raw_command_t>(ERR_NOSUCHNICK):
	case static_cast<raw_command_t>(ERR_NOSUCHSERVER):
	case static_cast<raw_command_t>(ERR_NOSUCHCHANNEL):
	case static_cast<raw_command_t>(ERR_CANNOTSENDTOCHAN):
	case static_cast<raw_command_t>(ERR_TOOMANYCHANNELS):
	case static_cast<raw_command_t>(ERR_WASNOSUCHNICK):
	case static_cast<raw_command_t>(ERR_TOOMANYTARGETS):
	case static_cast<raw_command_t>(ERR_NOSUCHSERVICE):
	case static_cast<raw_command_t>(ERR_NOORIGIN):
	case static_cast<raw_command_t>(ERR_NORECIPIENT):
	case static_cast<raw_command_t>(ERR_NOTEXTTOSEND):
	case static_cast<raw_command_t>(ERR_NOTOPLEVEL):
	case static_cast<raw_command_t>(ERR_WILDTOPLEVEL):
	case static_cast<raw_command_t>(ERR_NOTOPLEVEL):
	case static_cast<raw_command_t>(ERR_BADMASK):
	case static_cast<raw_command_t>(ERR_QUERYTOOLONG):
	case static_cast<raw_command_t>(ERR_UNKNOWNCOMMAND):
	case static_cast<raw_command_t>(ERR_NOMOTD):
	case static_cast<raw_command_t>(ERR_NOADMININFO):
	case static_cast<raw_command_t>(ERR_FILEERROR):
	case static_cast<raw_command_t>(ERR_NONICKNAMEGIVEN):
	case static_cast<raw_command_t>(ERR_ERRONEUSNICKNAME):
	case static_cast<raw_command_t>(ERR_NICKNAMEINUSE):
	case static_cast<raw_command_t>(ERR_SERVICECONFUSED):
	case static_cast<raw_command_t>(ERR_BANONCHAN):
	case static_cast<raw_command_t>(ERR_NICKCOLLISION):
	case static_cast<raw_command_t>(ERR_UNAVAILRESOURCE):
	case static_cast<raw_command_t>(ERR_DEAD):
	case static_cast<raw_command_t>(ERR_NICKTOOFAST):
	case static_cast<raw_command_t>(ERR_NCHANGETOOFAST):
	case static_cast<raw_command_t>(ERR_TARGETTOOFAST):
	case static_cast<raw_command_t>(ERR_SERVICESDOWN):
	case static_cast<raw_command_t>(ERR_USERNOTINCHANNEL):
	case static_cast<raw_command_t>(ERR_NOTONCHANNEL):
	case static_cast<raw_command_t>(ERR_USERONCHANNEL):
	case static_cast<raw_command_t>(ERR_NOLOGIN):
	case static_cast<raw_command_t>(ERR_SUMMONDISABLED):
	case static_cast<raw_command_t>(ERR_USERSDISABLED):
	case static_cast<raw_command_t>(ERR_NOTREGISTERED):
	case static_cast<raw_command_t>(ERR_NICKLOST):
	case static_cast<raw_command_t>(ERR_HOSTILENAME):
	case static_cast<raw_command_t>(ERR_NEEDMOREPARAMS):
	case static_cast<raw_command_t>(ERR_ALREADYREGISTRED):
	case static_cast<raw_command_t>(ERR_NOPERMFORHOST):
	case static_cast<raw_command_t>(ERR_PASSWDMISMATCH):
	case static_cast<raw_command_t>(ERR_YOUREBANNEDCREEP):
	case static_cast<raw_command_t>(ERR_YOUWILLBEBANNED):
	case static_cast<raw_command_t>(ERR_KEYSET):
	case static_cast<raw_command_t>(ERR_ONLYSERVERSCANCHANGE):
	case static_cast<raw_command_t>(ERR_CHANNELISFULL):
	case static_cast<raw_command_t>(ERR_UNKNOWNMODE):
	case static_cast<raw_command_t>(ERR_INVITEONLYCHAN):
	case static_cast<raw_command_t>(ERR_BANNEDFROMCHAN):
	case static_cast<raw_command_t>(ERR_BADCHANNELKEY):
	case static_cast<raw_command_t>(ERR_BADCHANMASK):
	case static_cast<raw_command_t>(ERR_NOCHANMODES):
	case static_cast<raw_command_t>(ERR_MODELESS):
	case static_cast<raw_command_t>(ERR_BANLISTFULL):
	case static_cast<raw_command_t>(ERR_NOPRIVILEGES):
	case static_cast<raw_command_t>(ERR_CHANOPRIVSNEEDED):
	case static_cast<raw_command_t>(ERR_CANTKILLSERVER):
	case static_cast<raw_command_t>(ERR_RESTRICTED):
	case static_cast<raw_command_t>(ERR_ISCHANSERVICE):
	case static_cast<raw_command_t>(ERR_UNIQOPPRIVSNEEDED):
	case static_cast<raw_command_t>(ERR_TSLESSCHAN):
	case static_cast<raw_command_t>(ERR_VOICENEEDED):
	case static_cast<raw_command_t>(ERR_NOOPERHOST):
	case static_cast<raw_command_t>(ERR_NOSERVICEHOST):
	case static_cast<raw_command_t>(ERR_UMODEUNKNOWNFLAG):
	case static_cast<raw_command_t>(ERR_USERSDONTMATCH):
	case static_cast<raw_command_t>(ERR_LAST_ERR_MSG):
	case static_cast<raw_command_t>(ERR_SILELISTFULL):
	case static_cast<raw_command_t>(ERR_NOSUCHGLINE):
	case static_cast<raw_command_t>(ERR_TOOMANYWATCH):
	case static_cast<raw_command_t>(ERR_BADPING):
	case static_cast<raw_command_t>(ERR_TOOMANYDCC):
	case static_cast<raw_command_t>(ERR_LISTSYNTAX):
	case static_cast<raw_command_t>(ERR_WHOSYNTAX):
	case static_cast<raw_command_t>(ERR_WHOLIMEXCEED):
	case static_cast<raw_command_t>(ERR_NUMERIC_ERR):
	case static_cast<raw_command_t>(error):
	case static_cast<raw_command_t>(join):
	case static_cast<raw_command_t>(kick):
	case static_cast<raw_command_t>(mode):
	case static_cast<raw_command_t>(nick):
	case static_cast<raw_command_t>(notice):
	case static_cast<raw_command_t>(part):
	case static_cast<raw_command_t>(ping):
	case static_cast<raw_command_t>(pong):
	case static_cast<raw_command_t>(privmsg):
	case static_cast<raw_command_t>(quit):
	case static_cast<raw_command_t>(topic):
		return static_cast<command>(value);
	}
}

} //namespace irc
